// packages/vue/src/components/Flex/Flex.vue
<script lang="ts">
    import { defineComponent } from "vue";
    import { useClasses } from "../../hooks/useClasses";
    import { useStyleConfig } from "../../hooks/useStyleConfig";
    import { FlexProps } from "./Flex";

    export default defineComponent({
        name: "RFlex",
        props: {
            direction: { type: String, default: "row" },
            wrap: { type: String, default: "no-wrap" },
            alignItems: { type: String, default: "start" },
            justifyContent: { type: String, default: "start" },
            alignContent: { type: String, default: "start" },
            inline: { type: Boolean, default: false },
            styleObj: Object,
            as: { type: String, default: "div" },
        },
        setup(_props) {
            const props = _props as FlexProps;
            const alignContent = props.alignContent;
            const alignItems = props.alignItems;
            const direction = props.direction;
            const inline = props.inline;
            const justifyContent = props.justifyContent;
            const wrap = props.wrap;
            const styleObj = props.styleObj;

            const flexStyleObj = useStyleConfig("Flex", styleObj);

            const classes = useClasses(
                flexStyleObj.default,
                { [flexStyleObj.inline]: inline },
                flexStyleObj.direction[direction],
                flexStyleObj.wrap[wrap],
                flexStyleObj.alignItems[alignItems],
                flexStyleObj.justifyContent[justifyContent],
                flexStyleObj.alignContent[alignContent],
            );

            return {
                classes,
            };
        },
    });
</script>

<template>
    <component :is="$props.as" :class="classes">
        <slot></slot>
    </component>
</template>

// packages/react/src/components/Flex/Flex.tsx
import PropTypes from "prop-types";
import React from "react";
import { forwardRef, HTMLRevindProps } from "utils/forward-ref";
import { FlexOptions } from "@revind/types";
import { useStyleConfig } from "hooks/useStyleConfig";
import { useClasses } from "hooks/useClasses";

export type FlexProps = HTMLRevindProps<"div"> & FlexOptions;

/**
 * Flex is a css flexbox wrapper. Its a core level component & shared
 * across multiple components. It supports both block & inline
 * implementation
 * @example
 * ```jsx
 * <Flex inline direction="column" justifyContent="center" alignItems="center">
 *    <button>Button 1</button>
 *    <button>Button 2</button>
 *    <button>Button 3</button>
 * </Flex>
 * ```
 */
export const Flex = forwardRef<FlexProps, "div">(function Flex(
    {
        direction = "row",
        wrap = "no-wrap",
        alignItems = "start",
        justifyContent = "start",
        alignContent = "start",
        inline = false,
        children,
        className,
        styleObj,
        ...props
    },
    ref,
) {
    const flexStyleObj = useStyleConfig("Flex", styleObj);

    const classes = useClasses(
        flexStyleObj.default,
        { [flexStyleObj.inline]: inline },
        flexStyleObj.direction[direction],
        flexStyleObj.wrap[wrap],
        flexStyleObj.alignItems[alignItems],
        flexStyleObj.justifyContent[justifyContent],
        flexStyleObj.alignContent[alignContent],
        className,
    );
    return (
        <div ref={ref} className={classes} {...props}>
            {children}
        </div>
    );
});

export const flexProps = {
    direction: PropTypes.oneOf<FlexProps["direction"]>([
        "column",
        "row",
        "row-reverse",
        "column-reverse",
    ]),

    wrap: PropTypes.oneOf<FlexProps["wrap"]>(["wrap", "no-wrap", "wrap-reverse"]),

    justifyContent: PropTypes.oneOf<FlexProps["justifyContent"]>([
        "center",
        "start",
        "end",
        "between",
        "around",
        "evenly",
    ]),

    alignContent: PropTypes.oneOf<FlexProps["alignContent"]>([
        "center",
        "start",
        "end",
        "between",
        "around",
        "evenly",
    ]),

    alignItems: PropTypes.oneOf<FlexProps["alignItems"]>([
        "center",
        "start",
        "end",
        "stretch",
        "baseline",
    ]),

    inline: PropTypes.bool,
};

Flex.propTypes = flexProps;
