// packages/react/src/components/Button/Button.tsx
import * as PropTypes from "prop-types";
import React, { ReactNode } from "react";
import clsx from "clsx";
import { forwardRef, HTMLRevindProps } from "utils/forward-ref";
import { ButtonOptions } from "@revind/types";
import { useStyleConfig } from "hooks/useStyleConfig";
import { useClasses } from "hooks/useClasses";

export type ReactRevindButtonOptions = ButtonOptions<ReactNode>;

export type ButtonProps = HTMLRevindProps<"button"> & ReactRevindButtonOptions;

/**
 * Higher level Button component
 */
export const Button = forwardRef<ButtonProps, "button">(function Button(
    {
        scheme = "primary",
        size = "md",
        margin: isMargin = true,
        variant = "filled",
        "start-icon": startIcon,
        "end-icon": endIcon,
        "full-width": isFullWidth = false,
        rounded: isRounded = true,
        as: Component = "button",
        styleObj,
        className,
        children,
        ...props
    },
    ref,
) {
    const {
        sizes,
        variantSchemes,
        variants,
        default: { start, end },
        sub: { startIcon: startIconStyle, endIcon: endIconStyle },
        schemes,
        conditionals: { fullWidth, margin, rounded },
        variantSizes,
    } = useStyleConfig("Button", styleObj);

    const classes = useClasses(
        start,
        variants[variant],
        sizes[size],
        schemes[scheme],
        variantSizes?.[variant]?.[size],
        variantSchemes?.[variant]?.[scheme],
        {
            [margin]: isMargin,
            [fullWidth]: isFullWidth,
            [rounded]: isRounded,
        },
        end,
        className,
    );

    return (
        <Component ref={ref} className={classes} {...props}>
            <span
                className={clsx(startIconStyle.default.start, startIconStyle.default.end)}
            >
                {startIcon}
            </span>
            {children}
            <span className={clsx(endIconStyle.default.start, endIconStyle.default.end)}>
                {endIcon}
            </span>
        </Component>
    );
});

Button.propTypes = {
    ...Button.propTypes,
    variant: PropTypes.oneOf<ButtonProps["variant"]>(["filled", "outlined", "minimal"]),
    scheme: PropTypes.oneOf<ReactRevindButtonOptions["scheme"]>([
        "primary",
        "secondary",
        "red",
        "green",
        "yellow",
    ]),
    size: PropTypes.oneOf<ReactRevindButtonOptions["size"]>([
        "sm",
        "md",
        "lg",
        "xl",
        "2xl",
    ]),
    margin: PropTypes.bool,
    "start-icon": PropTypes.node,
    "end-icon": PropTypes.node,
    "full-width": PropTypes.bool,
    rounded: PropTypes.bool,
};

// packages/vue/src/components/Button/Button.vue
<script lang="ts">
    import { useClasses } from "../../hooks/useClasses";
    import { defineComponent } from "vue";
    import { useStyleConfig, VueRevindProps } from "../../hooks/useStyleConfig";
    import { ButtonOptions } from "@revind/types";
    import { RequiredKey } from "../../types";

    export type VueRevindButtonOptions = Omit<
        ButtonOptions<unknown>,
        "start-icon" | "end-icon"
    >;

    export type ButtonProps = RequiredKey<
        VueRevindButtonOptions,
        "scheme" | "size" | "variant"
    > &
        VueRevindProps;

    export default defineComponent({
        name: "RButton",
        props: {
            "full-width": Boolean,
            margin: Boolean,
            rounded: { type: Boolean, default: true },
            scheme: { type: String, default: "primary" },
            size: { type: String, default: "md" },
            variant: { type: String, default: "filled" },
            styleObj: Object,
            as: { type: String, default: "button" },
        },
        setup(_props) {
            const props = _props as ButtonProps;
            const isFullWidth = props["full-width"] ?? false;
            const isMargin = props.margin ?? false;
            const isRounded = props.rounded ?? true;
            const scheme = props.scheme;
            const size = props.size;
            const variant = props.variant;
            const styleObj = props.styleObj;

            const {
                default: { start, end },
                sizes,
                variantSchemes,
                variants,
                schemes,
                variantSizes,
                sub: { startIcon, endIcon },
                conditionals: { fullWidth, margin, rounded },
            } = useStyleConfig("Button", styleObj);

            const classes = useClasses(
                start,
                variants[variant],
                sizes[size],
                schemes[scheme],
                variantSizes?.[variant]?.[size],
                variantSchemes?.[variant]?.[scheme],
                {
                    [margin]: isMargin,
                    [fullWidth]: isFullWidth,
                    [rounded]: isRounded,
                },
                end,
            );

            const startIconClasses = [startIcon.default.start, startIcon.default.end];
            const endIconClasses = [endIcon.default.start, endIcon.default.end];
            return {
                classes,
                startIconClasses,
                endIconClasses,
            };
        },
    });
</script>

<template>
    <component :is="$props.as" :class="classes">
        <slot name="startIcon" :class="startIconClasses"> </slot>
        <slot></slot>
        <slot name="endIcon" :class="endIconClasses"> </slot>
    </component>
</template>
