// packages/vue/src/components/ButtonGroup/ButtonGroup.vue
<script lang="ts">
    import { defineComponent } from "vue";
    import { useStyleConfig } from "../../hooks/useStyleConfig";
    import { ButtonGroupProps } from "./ButtonGroup";
    import Flex from "../Flex/Flex.vue";
    import clsx from "clsx";

    export default defineComponent({
        name: "RButtonGroup",
        components: { Flex },
        props: {
            "full-width": {
                type: Boolean,
                default: false,
            },
            direction: {
                type: String,
                default: "row",
            },
            size: {
                type: String,
                default: "md",
            },
            variant: {
                type: String,
                default: "filled",
            },
            scheme: {
                type: String,
                default: "primary",
            },
            styleObj: Object,
            as: { type: String, default: "div" },
        },
        setup(_props) {
            const props = _props as ButtonGroupProps;
            const direction = props.direction;
            const scheme = props.scheme;
            const size = props.size;
            const variant = props.variant;
            const styleObj = props.styleObj;

            const {
                borderColors,
                directions,
                variantDirections,
                default: { start, end },
            } = useStyleConfig("ButtonGroup", styleObj);

            return {
                classes: clsx(
                    start,
                    directions[direction],
                    variantDirections[variant]?.[direction],
                    borderColors?.[scheme],
                    end,
                ),
                scheme,
                size,
                variant,
            };
        },
    });
</script>

<template>
    <Flex
        role="group"
        align-items="stretch"
        :as="$props.as"
        :inline="!$props['full-width']"
        :direction="$props.direction"
    >
        <slot
            :class="classes"
            :size="size"
            :variant="variant"
            :scheme="scheme"
            :rounded="false"
            :margin="false"
        ></slot>
    </Flex>
</template>

// packages/react/src/components/ButtonGroup/ButtonGroup.tsx
import { ButtonGroupOptions } from "@revind/types";
import clsx from "clsx";
import PropTypes from "prop-types";
import React, { ReactNode } from "react";
import { isFragment } from "react-is";
import { Flex } from "components/Flex/Flex";
import { useStyleConfig } from "hooks/useStyleConfig";
import { forwardRef, HTMLRevindProps } from "utils/forward-ref";

export type ReactRevindButtonGroupOptions = ButtonGroupOptions<ReactNode>;

export type ButtonGroupProps = HTMLRevindProps<"div"> & ReactRevindButtonGroupOptions;

export const ButtonGroup = forwardRef<ButtonGroupProps, "div">(function ButtonGroup(
    {
        scheme = "primary",
        size = "md",
        variant = "filled",
        "full-width": fullWidth = false,
        direction = "row",
        styleObj,
        className,
        children,
        ...props
    },
    ref,
) {
    const {
        borderColors,
        directions,
        variantDirections,
        default: { start, end },
    } = useStyleConfig("ButtonGroup", styleObj);
    return (
        <Flex
            ref={ref as any}
            role="group"
            inline={!fullWidth}
            alignItems="stretch"
            className={className}
            direction={direction}
            {...props}
        >
            {React.Children.map(children, (child) => {
                if (!React.isValidElement(child)) {
                    return null;
                }

                if (process.env.NODE_ENV !== "production") {
                    if (isFragment(child)) {
                        throw new TypeError(
                            "[revind]: Fragments can't be use. Pass an array instead",
                        );
                    }
                }
                return React.cloneElement(child, {
                    className: clsx(
                        start,
                        directions[direction],
                        variantDirections[variant]?.[direction],
                        borderColors?.[scheme],
                        end,
                    ),
                    scheme,
                    size,
                    variant,
                    rounded: false,
                    margin: false,
                });
            })}
        </Flex>
    );
});

ButtonGroup.propTypes = {
    "full-width": PropTypes.bool,
    direction: PropTypes.oneOf<ReactRevindButtonGroupOptions["direction"]>([
        "row",
        "column",
    ]),
    size: PropTypes.oneOf<ReactRevindButtonGroupOptions["size"]>([
        "sm",
        "md",
        "lg",
        "xl",
        "2xl",
    ]),
    variant: PropTypes.oneOf<ReactRevindButtonGroupOptions["variant"]>([
        "filled",
        "outlined",
        "minimal",
    ]),
    scheme: PropTypes.oneOf<ReactRevindButtonGroupOptions["scheme"]>([
        "primary",
        "secondary",
        "red",
        "green",
        "yellow",
    ]),
};
